### ISSUE TITLE
[FEATURE_REQUEST] Добавить 2025г.

### ISSUE THREAD

**Issue by nordeep** [hywax/production-calendar#29]
### Describe the solution you'd like

Спасибо за вашу работу! Есть ли возможность добавить данные на 2025г.?

### Priority

High (The app does not function without it)

### Is this something you would be keen to implement

No

**Comment by hywax-assistant** [comment]
👋 @nordeep
Thanks for opening your first issue here!
We'll try to help you as soon as possible.

 If you like this project, please ⭐ star our repo.

**Comment by hywax** [comment]
Добавил получение текущего года + 1. Сейчас в репозитории файлы с календарями будут обновляться автоматически
